FROM nginx

LABEL version="1.0"

WORKDIR /usr/share/nginx/html

COPY ./exo_site/. .

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]

# docker build -t my-website-nginx .

# docker run -p 8000:80 --name mywebsite -d my-website-nginx

# docker tag my-website-nginx alexandremessuvem2i/my-website-nginx:1.0

# docker push alexandremessuvem2i/my-website-nginx:1.0